# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteChapter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votechapter',
            name='rating',
            field=models.FloatField(max_length=11),
        ),
    ]
