# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('idReader_id', models.CharField(max_length=20)),
                ('idBook_id', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(max_length=50)),
            ],
            options={
                'db_table': 'collection',
            },
        ),
    ]
