# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reader',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name=b'\xe7\xb7\xa8\xe8\x99\x9f')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb6\xe5\x90\x8d')),
                ('passwd', models.CharField(max_length=100, unique=True, verbose_name=b'\xe5\xaf\x86\xe7\xa2\xbc')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name=b'\xe9\x9b\xbb\xe5\xad\x90\xe9\x83\xb5\xe7\xae\xb1')),
                ('status', models.CharField(choices=[(b'allowed', b'allowed'), (b'abuse', b'abuse'), (b'locked', b'locked')], max_length=20, verbose_name=b'\xe8\xb3\xac\xe8\x99\x9f\xe7\x8b\x80\xe6\x85\x8b')),
                ('createTime', models.DateTimeField(max_length=50, verbose_name=b'\xe7\x94\xb3\xe8\xab\x8b\xe6\x99\x82\xe9\x96\x93')),
            ],
            options={
                'db_table': 'reader',
                'verbose_name': '\u8b80\u8005\u8868',
                'verbose_name_plural': '\u8b80\u8005\u5217\u8868\u7ba1\u7406',
            },
        ),
    ]
