# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reader',
            options={'verbose_name': '\u8b80\u8005', 'verbose_name_plural': '\u8b80\u8005\u5217\u8868\u7ba1\u7406'},
        ),
    ]
