# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name=b'\xe7\xb7\xa8\xe8\x99\x9f')),
                ('status', models.CharField(choices=[(b'active', b'active'), (b'inactive', b'inactive'), (b'locked', b'locked')], max_length=20, verbose_name=b'\xe8\xb3\xac\xe8\x99\x9f\xe7\x8b\x80\xe6\x85\x8b')),
                ('createTime', models.DateTimeField(max_length=50, verbose_name=b'\xe7\x94\xb3\xe8\xab\x8b\xe6\x99\x82\xe9\x96\x93')),
                ('idReader_id', models.CharField(max_length=20, unique=True, verbose_name=b'\xe8\xae\x80\xe8\x80\x85\xe7\xb7\xa8\xe8\x99\x9f')),
            ],
            options={
                'db_table': 'author',
                'verbose_name': '\u4f5c\u8005\u8868',
                'verbose_name_plural': '\u4f5c\u8005\u5217\u8868\u7ba1\u7406',
            },
        ),
    ]
