#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Django settings for WeArt project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import socket

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0(5p$h=5c3fve1n$b9j!#fuhif7a4-2jn#^ze(=jt%bz^(+q%r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '140.118.155.82']


# Application definition
TEST_DATABASE_NAME = "test_weArt"
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django-dia',

    'recommand',
    'author',
    'book',
    'chapter',
    'collection',
    'content',
    'home',
    'reader',
    'tool',
    'version',
    'voteChapter',
    'WeArt',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',   # enable the gzip
)

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
LANGUAGE_CODE = 'zh-hant'
USE_I18N = True
LANGUAGES = (
    ('en', ('English')),
    ('zh-hans', ('中文简体')),
    ('zh-hant', ('中文繁體')),
)

ROOT_URLCONF = 'WeArt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + "/templates",],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WeArt.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # or use ' mysql.connector.django ''
        'NAME': 'weArt',
        'USER': 'root',
        'PASSWORD': 'lidaxiang',
        'HOST':'localhost',
        'PORT':'3306',
        'OPTIONS':{
            "init_command": "SET default_storage_engine=MyISAM",
            'charset': 'utf8',
        },
    }
}

# if USE_TZ is True,the database must store the UTC time
USE_TZ = False
TIME_ZONE = 'Asia/Shanghai'
USE_L10N = True # local first

# ADMIN_MEDIA_PREFIX = '/static/admin/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
# STATIC_URL = '/static/'
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_ROOT = '/etc/nginx/html/WeArt/djangoStatic/'
STATIC_URL = '/static/'
STATICFILES_DIRS =[ os.path.join(BASE_DIR, 'static'), ]

# session settings
SESSION_COOKIE_AGE = 60*60*24
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# SESSION_FILE_PATH = "/home/lidaxiang/WeArtSession"

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'weartRegister@gmail.com'
EMAIL_HOST_PASSWORD = 'weArt2017'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DOMAIN = "127.0.0.1:8000"

# This is remote GIT server ip address.And it needs to be changed when changing git-server.
GIT_SERVER_IP = "192.168.122.171"   # lab server git-server ip
# GIT_SERVER_IP = "172.16.153.128"   # my loacl git-server ip
GIT_SERVER_USER = "lidaxiang"
GIT_SERVER_USERPASSWD = "lidaxiang"

# the port when user register to become reader
REGISTER_SERVER_DOMAIN = socket.gethostbyname(socket.gethostname()) + ":8000"

# the books classied root directory in git-server and web-server
BOOKS_ROOT_DIR = "/home/lidaxiang"
