-- MySQL Script generated by MySQL Workbench
-- 2018年01月03日 星期三 17时58分41秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema weArt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `weArt` ;

-- -----------------------------------------------------
-- Schema weArt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weArt` DEFAULT CHARACTER SET utf8 ;
USE `weArt` ;

-- -----------------------------------------------------
-- Table `weArt`.`reader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weArt`.`reader` ;

CREATE TABLE IF NOT EXISTS `weArt`.`reader` (
  `id` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NULL,
  `passwd` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `status` VARCHAR(20) NULL,
  `createTime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weArt`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weArt`.`admin` ;

CREATE TABLE IF NOT EXISTS `weArt`.`admin` (
  `id` VARCHAR(5) NOT NULL,
  `name` VARCHAR(45) NULL,
  `passwd` VARCHAR(45) NULL,
  `status` VARCHAR(20) NULL,
  `createTime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `weArt`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weArt`.`book` ;

CREATE TABLE IF NOT EXISTS `weArt`.`book` (
  `id` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NULL,
  `remoteIP` VARCHAR(20) NULL,
  `location` VARCHAR(100) NULL,
  `chapterCount` INT NULL,
  `status` VARCHAR(20) NULL,
  `createTime` DATETIME NULL,
  `idReader_id` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weArt`.`chapter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weArt`.`chapter` ;

CREATE TABLE IF NOT EXISTS `weArt`.`chapter` (
  `id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(45) NULL,
  `fileName` VARCHAR(100) NULL,
  `chapterOrder` INT NULL,
  `status` VARCHAR(20) NULL,
  `createTime` DATETIME NULL,
  `idBook_id` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `weArt`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weArt`.`author` ;

CREATE TABLE IF NOT EXISTS `weArt`.`author` (
  `id` VARCHAR(15) NOT NULL,
  `status` VARCHAR(20) NULL,
  `createTime` DATETIME NULL,
  `idReader_id` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weArt`.`collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weArt`.`collection` ;

CREATE TABLE IF NOT EXISTS `weArt`.`collection` (
  `id` VARCHAR(30) NOT NULL,
  `idReader_id` VARCHAR(20) NULL,
  `idBook_id` VARCHAR(20) NULL,
  `createTime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weArt`.`recommend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weArt`.`recommend` ;

CREATE TABLE IF NOT EXISTS `weArt`.`recommend` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `idBook_id` VARCHAR(20) NULL,
  `order` INT NULL,
  `location` VARCHAR(50) NULL,
  `class` VARCHAR(50) NULL,
  `status` VARCHAR(10) NULL,
  `createTime` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weArt`.`version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weArt`.`version` ;

CREATE TABLE IF NOT EXISTS `weArt`.`version` (
  `id` VARCHAR(50) NOT NULL,
  `idChapter_id` VARCHAR(30) NULL,
  `voteCount` DOUBLE NULL,
  `score` DOUBLE NULL,
  `idAuthor_id` VARCHAR(20) NULL,
  `createTime` DATETIME NULL,
  `modifyTime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `weArt`.`voteChapter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weArt`.`voteChapter` ;

CREATE TABLE IF NOT EXISTS `weArt`.`voteChapter` (
  `id` VARCHAR(50) NOT NULL,
  `idReader_id` VARCHAR(20) NOT NULL,
  `idVersion` VARCHAR(50) NOT NULL,
  `rating` DOUBLE NOT NULL,
  `createTime` DATETIME NOT NULL,
  `modifyTime` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
