-- MySQL Script generated by MySQL Workbench
-- 2017年07月20日 星期四 17时41分09秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema weArt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `weArt` ;

-- -----------------------------------------------------
-- Schema weArt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weArt` DEFAULT CHARACTER SET utf8 ;
USE `weArt` ;

-- -----------------------------------------------------
-- Table `weArt`.`reader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weArt`.`reader` ;

CREATE TABLE IF NOT EXISTS `weArt`.`reader` (
  `id` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NULL,
  `passwd` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `status` VARCHAR(20) NULL,
  `createTime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `weArt`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weArt`.`admin` ;

CREATE TABLE IF NOT EXISTS `weArt`.`admin` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `passwd` VARCHAR(45) NULL,
  `status` VARCHAR(20) NULL,
  `createTime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `weArt`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weArt`.`author` ;

CREATE TABLE IF NOT EXISTS `weArt`.`author` (
  `id` VARCHAR(20) NOT NULL,
  `status` VARCHAR(20) NULL,
  `createTime` DATETIME NULL,
  `idReader` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_author_1_idx` (`idReader` ASC),
  CONSTRAINT `fk_author_1`
    FOREIGN KEY (`idReader`)
    REFERENCES `weArt`.`reader` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weArt`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weArt`.`book` ;

CREATE TABLE IF NOT EXISTS `weArt`.`book` (
  `id` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NULL,
  `remoteIP` VARCHAR(20) NULL,
  `status` VARCHAR(20) NULL,
  `createTime` DATETIME NULL,
  `idAuthor` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_book_1_idx` (`idAuthor` ASC),
  CONSTRAINT `fk_book_1`
    FOREIGN KEY (`idAuthor`)
    REFERENCES `weArt`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weArt`.`chapter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weArt`.`chapter` ;

CREATE TABLE IF NOT EXISTS `weArt`.`chapter` (
  `id` VARCHAR(30) CHARACTER SET 'cp850' NOT NULL,
  `name` VARCHAR(45) NULL,
  `fileName` VARCHAR(100) NULL,
  `chapterOrder` INT NULL,
  `status` VARCHAR(20) NULL,
  `createTime` DATETIME NULL,
  `idBook` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chapter_1_idx` (`idBook` ASC),
  CONSTRAINT `fk_chapter_1`
    FOREIGN KEY (`idBook`)
    REFERENCES `weArt`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weArt`.`collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weArt`.`collection` ;

CREATE TABLE IF NOT EXISTS `weArt`.`collection` (
  `id` VARCHAR(30) NOT NULL,
  `idReader` VARCHAR(20) NULL,
  `idBook` VARCHAR(20) NULL,
  `createTime` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_collection_1_idx` (`idReader` ASC),
  INDEX `fk_collection_2_idx` (`idBook` ASC),
  CONSTRAINT `fk_collection_1`
    FOREIGN KEY (`idReader`)
    REFERENCES `weArt`.`reader` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_collection_2`
    FOREIGN KEY (`idBook`)
    REFERENCES `weArt`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
