# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name=b'\xe7\xb7\xa8\xe8\x99\x9f')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe6\x9b\xb8\xe5\x90\x8d')),
                ('remoteIP', models.GenericIPAddressField(default=b'192.168.0.1', verbose_name=b'\xe9\x81\xa0\xe7\xab\xaf\xe5\x80\x89\xe5\xba\xabIP')),
                ('location', models.CharField(max_length=20, verbose_name=b'\xe5\xad\x98\xe5\x84\xb2\xe4\xbd\x8d\xe7\xbd\xae')),
                ('chapterCount', models.IntegerField(verbose_name=b'\xe7\xab\xa0\xe7\xaf\x80\xe6\x95\xb8\xe9\x87\x8f')),
                ('status', models.CharField(choices=[(b'active', b'active'), (b'inactive', b'inactive'), (b'locked', b'locked')], max_length=20, verbose_name=b'\xe7\x8b\x80\xe6\x85\x8b')),
                ('createTime', models.DateTimeField(max_length=50, verbose_name=b'\xe5\x89\xb5\xe5\xbb\xba\xe6\x99\x82\xe9\x96\x93')),
                ('idReader_id', models.CharField(max_length=30, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85\xe7\xb7\xa8\xe8\x99\x9f')),
            ],
            options={
                'db_table': 'book',
                'verbose_name': '\u66f8\u7c4d\u8868',
                'verbose_name_plural': '\u66f8\u7c4d\u5217\u8868\u7ba1\u7406',
            },
        ),
    ]
