# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20171015_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '\u66f8\u7c4d', 'verbose_name_plural': '\u66f8\u7c4d\u5217\u8868\u7ba1\u7406'},
        ),
    ]
