# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fileName', models.CharField(max_length=20)),
                ('chapterOrder', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(max_length=50)),
                ('idBook_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
    ]
