# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='fileName',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
