# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('idChapter_id', models.CharField(max_length=30)),
                ('voteCount', models.PositiveIntegerField()),
                ('score', models.FloatField(max_length=11)),
                ('idAuthor_id', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(max_length=50)),
                ('modifyTime', models.DateTimeField(max_length=50)),
            ],
            options={
                'db_table': 'version',
            },
        ),
    ]
