# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommand',
            name='idBook_id',
            field=models.CharField(max_length=20, unique=True, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb6\xe5\x90\x8d'),
        ),
    ]
