# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommand', '0002_auto_20171015_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommand',
            name='idBook_id',
            field=models.CharField(max_length=20, unique=True, verbose_name=b'\xe6\x9b\xb8\xe7\xb1\x8dId'),
        ),
    ]
