# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommand', '0005_auto_20171015_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommand',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, max_length=50, verbose_name=b'\xe7\x94\xb3\xe8\xab\x8b\xe6\x99\x82\xe9\x96\x93'),
        ),
        migrations.AlterField(
            model_name='recommand',
            name='modifyTime',
            field=models.DateTimeField(auto_now=True, max_length=50, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x99\x82\xe9\x96\x93'),
        ),
    ]
