# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommand', '0010_auto_20171015_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommand',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
