# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommand', '0012_auto_20171015_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommand',
            name='id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
